name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

# The sequence of jobs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out the repository so the job can access it
      - uses: actions/checkout@v4  # Updated to v4 which uses Node 20

      # Generates the snake GIF and SVG files
      - uses: Platane/snk@master  # Using the master branch of the action
        id: snake-gif
        with:
          github_user_name: tarunj292
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build to assist with debugging (if any issues arise)
      - run: git status

      # Push the generated files to the master branch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Deploy the generated files to the "output" branch for GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
